import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from  "../components/Navbar"
import Footer from "../components/Footer"


const inter = Inter({
  subsets: ["latin"], // Adjust for languages if needed
   // Include desired weights
});

export const metadata: Metadata = {
  title: "Falcon",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className } >
        
       <div className="nav-gradient">
       <Navbar />
       </div>
        
       
        <main className="bg-[#080808] font-poppins">
        {children}
        </main >
        <div className="bg-[#080808]">
        <Footer />
        </div>
      
        
        </body>
    </html>
  );
}
