import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Navbar from  "../components/Navbar"
import Footer from "../components/Footer"


const poppins = Poppins({
  subsets: ["latin"], // Adjust for languages if needed
  weight: ['300', '400', '500', '600', '700'], // Include desired weights
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={poppins.className } >
        
        <Navbar />
        
       
        <main className="bg-[#080808]">
        {children}
        </main >
        <div className="bg-[#080808]">
        <Footer />
        </div>
      
        
        </body>
    </html>
  );
}
